# Generated by Django 4.2.4 on 2023-10-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='sentimiento',
            field=models.CharField(blank=True, choices=[('alegre', 'Alegre'), ('triste', 'Triste'), ('neutro', 'Neutro'), ('enojado', 'Enojado')], max_length=10, null=True),
        ),
    ]
