# Generated by Django 4.2.4 on 2023-10-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_reservacita'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacita',
            name='estatus',
            field=models.CharField(choices=[('Agendada', 'Agendada'), ('Aceptada', 'Aceptada'), ('En progreso', 'En progreso'), ('En espera de recogida de vehículo', 'En espera de recogida de vehículo'), ('Terminada', 'Terminada')], default='Agendada', max_length=50),
        ),
    ]
