# Generated by Django 4.2.4 on 2023-10-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_reservacita_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacita',
            name='estatus',
            field=models.CharField(choices=[('Agendada', 'Agendada'), ('Cancelada', 'Cancelada'), ('En espera de entrega de vehículo', 'En espera de entrega de vehículo'), ('En progreso', 'En progreso'), ('En espera de recogida de vehículo', 'En espera de recogida de vehículo'), ('Terminada', 'Terminada')], default='Agendada', max_length=50),
        ),
    ]
