# Generated by Django 4.2.4 on 2023-10-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_extendeddata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
