# Generated by Django 4.2.4 on 2023-10-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_service_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeddata',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
