# Generated by Django 4.2.4 on 2023-10-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_extendeddata_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeddata',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='extendeddata',
            name='direccion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
